### ISSUE TITLE
Examples crash due to winit version

### ISSUE THREAD

**Issue by dmyyy** [olson-sean-k/plexus#114]
https://github.com/rust-windowing/winit/issues/1782

Updating to 0.24.0+ should fix this.

As an aside I'm curious about the use cases for this crate - am I correct in thinking it is primarily used for runtime procedural mesh generation? 

Edit: Most of the docs refer to things being in an initial development state - was wondering about what the long term plans look like for this crate.

**Comment by virtualritz** [comment]
> As an aside I'm curious about the use cases for this crate - am I correct in thinking it is primarily used for runtime procedural mesh generation?

Yes.

My take is that this crate is a gem that no one uses because of lack of (updated/complete) documentation and [examples](https://github.com/olson-sean-k/plexus/issues/14).

See recent projects that use a half-edge data structure for mesh representation but rolled their own.
Of the to of my head: [blackjack](https://github.com/setzer22/blackjack), [fornjot](https://github.com/hannobraun/fornjot), [truck](https://github.com/ricosjp/truck). I would be surprised if not at least some of them did have a good look at `plexus` at some stage.

**Comment by olson-sean-k** [comment]
Thanks for reporting this, @dmyyy! I just fixed some issues on `master` in CI and just have a small nitpick in the PR. Please take a look.

> As an aside I'm curious about the use cases for this crate - am I correct in thinking it is primarily used for runtime procedural mesh generation?

As @virtualritz has already confirmed, that is indeed one of the intended use cases, yes! This whole mess started when I wanted to generate cuboid meshes in a small learning project. Oops.

> Most of the docs refer to things being in an initial development state - was wondering about what the long term plans look like for this crate.

I still think of this crate (and some of the direct dependencies that I maintain) as experimental. I'm not too experienced in this space and I've been trying to take what I can learn and try some fresh approaches while leveraging some of the advantages that Rust brings to the table. I do plan to continue development when I can find time and eventually publish releases. One pipe dream I have is to implement some 3D modeling software powered by Plexus.

> My take is that this crate is a gem...

Thanks! :smile: I think there are some very questionable things in this crate, but there are at least a few things that I'm honestly quite happy with too.

> ...no one uses because of lack of (updated/complete) documentation and examples.

I definitely agree that the lack of guides and other documentation hasn't been great. There's still a whole lot that I'd like to settle on and stabilize and I've been hesitant to write higher level guides before I'm satisfied with that work.

**Comment by virtualritz** [comment]
> One pipe dream I have is to implement some 3D modeling software powered by Plexus.

I'm very interested in contributing to a Rust-powered 3D modeling DCC. Something like [`blackjack`](https://github.com/setzer22/blackjack) but a tad more sophisticated.

I am thinking something like [Wings3D](http://www.wings3d.com/), [Houdini geometry nodes](https://www.sidefx.com/docs/houdini/nodes/sop/) and [Fugu](https://arxiv.org/pdf/2004.10354.pdf) having a baby.

Another thing that is currently not available is an app where you can blend traditional mesh-based modeling with SDF stuff.
I.e. this but get out minimal dense geometry. E.g. something where the SDF is meshed and then re-topologized into a minimal quad mesh that, when rendered as a (Catmull-Clark) subdivision surface approximates the original SDF as closely as possible.

Current SDF modelers export sub-par geometry. A favorite of mine in terms of UX/presentation is e.g. Womp](https://womp.com/).

If 3D SDFs in Rust interest you, keep an eye out for Matt Keeters' [`fidget`](https://github.com/mkeeter/fidget).
