### ISSUE TITLE
Subdividing mesh faces

### ISSUE THREAD

**Issue by Ralith** [olson-sean-k/plexus#20]
I have a mesh where every face is an equilateral triangle, and I want to replace every triangle with four smaller equal-sized triangles. In theory this should be straightforward with a half-edge data structure: subdivide every edge, then for each new vertex, add an edge to the vertex two steps along each incident edge loop, then fill in the new faces and erase the old ones.

The half-edge data structure provided by plexus, however, doesn't seem to expose a way to do this; I can subdivide edges easily enough, but introducing totally new edges and adding/removing faces appears to be impossible. There's a `triangulate` method which does something similar, but it relies on private interfaces to work. What's the intended approach for this sort of problem?

**Comment by olson-sean-k** [comment]
Thanks for opening an issue. You're correct: Plexus doesn't expose the topological mutations you'd need to achieve this right now. One of my initial goals was to avoid and discourage the use of low-level topological mutations, as it is very easy to end up with invalid topologies. That is why low-level mutations are not a part of the public API right now.

However, a half-edge graph is far less useful without exposing such basic topological operations and Plexus cannot predict all of the high-level operations that users will want to perform! To that end, I've been working on creating a transactional mutation API that I can re-export as part of the public API for Plexus. I want to avoid requiring user code to manually perform validation or, worse yet, allow user code to simply forget to perform that validation. I'm designing the mutation API to prevent this, but it's incomplete and hasn't been exposed yet. Once the mutation API is ready, this kind of subdividing should be possible.

If you're interested, you may want to take a look at the `graph::mutation` module to get an idea of what that API will look like.

**Comment by olson-sean-k** [comment]
I'm still holding on to some hope that the mutation API won't need to be exposed. I've been kicking up a bit of dust in the meantime. While I'm still exploring this, you may find [this example](https://github.com/olson-sean-k/plexus/blob/8cc191c5fb3b344b5497ed4f44035a1514b9e86a/examples/subdivide.rs#L16) interesting. It uses edge splitting and face bisecting to subdivide faces in a graph as you've described. The `subdivide` function in that example should enscribe a face with equal arity within any other face.

**Comment by Ralith** [comment]
That looks pretty promising, thanks! I'm off playing with transport protocols at the moment, but I'll try to remember to give that a try next time something similar comes up.
