### ISSUE TITLE
master build broken

### ISSUE THREAD

**Issue by virtualritz** [olson-sean-k/plexus#23]
```
$ cargo build --release
    [...]
   Compiling plexus v0.0.10 (/Users/moritz/code/plexus)
error[E0599]: no method named `clone` found for type `arrayvec::IntoIter<[graph::storage::VertexKey; 2]>` in the current scope
   --> src/graph/view/edge.rs:801:31
    |
801 |             input: self.input.clone(),
    |                               ^^^^^

error[E0599]: no method named `clone` found for type `arrayvec::IntoIter<[graph::storage::FaceKey; 2]>` in the current scope
   --> src/graph/view/edge.rs:879:31
    |
879 |             input: self.input.clone(),
    |                               ^^^^^

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `plexus`.
```

**Comment by olson-sean-k** [comment]
Yikes! I'm not able to look into this at the moment, but my guess is that the version constraints on the `arrayvec` crate are wrong and aren't picking up `Clone` implementations.

Does `$ cargo update` work around the problem?

**Comment by olson-sean-k** [comment]
It looks like `Clone` implementations for the `IntoIter` type landed in `0.4.8` of `arrayvec`, but Plexus depended on `0.4.*`. This should be fixed by 3b98129, which changes the dependency specification to `^0.4.8`.

**Comment by virtualritz** [comment]
Confirmed, https://github.com/olson-sean-k/plexus/commit/3b981295e7ce7ee7831b2320d024f88a417551bd fixes this.

**Comment by virtualritz** [comment]
Thanks for the quick fix!!! :)
