### ISSUE TITLE
Support ultraviolet crate

### ISSUE THREAD

**Issue by virtualritz** [olson-sean-k/plexus#61]
Since you already support three other linear algebra crates ... :)
https://github.com/termhn/ultraviolet

**Comment by olson-sean-k** [comment]
I've been planning to integrate with both `ultraviolet` and [`glam`](https://github.com/bitshifter/glam-rs) for a while now and just haven't gotten around to it. 😅 I definitely think these crates should be supported.

It shouldn't take too much effort to support these crates. The vast majority of the work has to happen in [Theon](https://github.com/olson-sean-k/theon) first (and there's already a branch with initial support for `glam`). After that, Plexus just needs to expose its own feature flags to enable the integrations.

**Comment by olson-sean-k** [comment]
Support for `glam` landed in [9b13020](https://github.com/olson-sean-k/theon/commit/9b13020458d34d0fb08feb8a7db98e7be63f12bc) and there's [a branch](https://github.com/olson-sean-k/theon/tree/ultraviolet) with some initial changes to support `ultraviolet`.

I'm not entirely sure yet how `ultraviolet`'s wide types (e.g., `Wec3`) should be handled. Unlike `glam`, these wide types use SIMD for an SoA approach that multiplexes work per component. At the moment, I think the most reasonable thing to do would be to expose the first element of each `f32x4` component as the scalar component in Theon's traits.

**Comment by olson-sean-k** [comment]
Initial support for `ultraviolet` landed in [3b3f062](https://github.com/olson-sean-k/theon/commit/3b3f0621c192a6df8bde39c461c90c383f2034d6). :tada: This only includes support for `Vec2` and `Vec3`, but should be enough for basic use as positional data. There's more work to do, but I plan to upgrade Plexus' dependency on Theon to pull in initial support for these crates.

**Comment by virtualritz** [comment]
Awesome! :)

**Comment by olson-sean-k** [comment]
Support for `glam` and `ultraviolet` landed in 346ade9. :tada: Again, this is not as complete as it could be, but geometric APIs work for two- and three-dimensional vector types from both crates. Feel free to reopen this issue if there's something specific that is missing.
